### PR TITLE
Fixes #6

### LINKED ISSUE #6: ESM - ECMAScript Modules with JavaScript mock data
**Describe the issue**
Node.js cannot be configured to ECMAScript modules (ESM) with a JavaScript mock data file.

JavaScript mock data must use CommonJS (CJS) export syntax `module.exports` with Node.js configured to support CJS (in package.json `type` must be omitted or set to "commonjs")

If Node.js is configured to ESM then the JavaScript mock data hits an exception on this [line 75](https://github.com/architect/plugin-lambda-invoker/blob/v1.0.1/src/index.js#L75)

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Update **packge.json** to `"type": "module",`
2. Touch a file in the root with filename `sandbox-invoke-mocks.js`
3. Define a mock structure with `module.exports` as _.CJS_ or `export default` syntax _.JS_ or _.MJS_

**Expected behaviour**
Execute lambda function with mock data

**Actual behaviour**

An empty mock event is passed to the Lambda function if the JavaScript mock file is a _.CJS_

ESM error if the JavaScript mock file is a _.JS_ or _.MJS_
```
/Users/.../node_modules/@architect/plugin-lambda-invoker/src/index.js:75
            mocks = require(jsMocks)
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/.../sandbox-invoke-mocks.js from /Users/.../node_modules/@architect/plugin-lambda-invoker/src/index.js not supported.

```

**Screenshots**
If applicable, add screenshots to help explain your problem

Screenshot 2023-08-07 at 13 07 31

**Environment**
Please complete the following information (if appropriate):
 - OS: macOS Ventura 13.4 (with Apple Silicon chip)
 - Node.js: v18 (LTS)

**Workaround**
Node.js may be configured as ESM then use a JSON file for your mock data (to avoid the `import`/`require` conflict)!

### PR DESCRIPTION
**Pull request by ryanblock**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `master`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -65,14 +67,18 @@ module.exports = {
           let pragma, name, mocks, skipSelection
 
           // Load invocation mocks
-          if (existsSync(jsonMocks)) {
+          /**/ if (existsSync(jsonMocks)) {
```
Comment (danactive) [inline src/index.js:70]: Is the comment needed?
```suggestion
          if (existsSync(jsonMocks)) {
```

**Review by danactive — APPROVED** [review]
👍🏼

File: src/index.js (hunk 1 above)
Comment (ryanblock) [reply src/index.js:70]: Needed? Nah, just a dumb little thing I do to align a series of `if` / `else if` conditions. 😅
